# More option see https://github.com/DreamMaoMao/mango/wiki/

# source for the seperations
source=./keybindings.conf
source=./exec.conf
source=./monitor.conf
source=./fx.conf
source=./input.conf
source=./look.conf
#source=./windowrule.conf
source=./layout.conf


# This sources the noctalia theme

source = /home/theycreeper/.config/mango/noctalia.conf

#source=../xdg-desktop-portal/portals.conf
