# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER,r,reload_config

# apps
bind=Alt,Return,spawn,foot
bind=Alt,b,spawn,brave
bind=Super,s,spawn,qs -c noctalia-shell ipc call settings toggle
bind=Super+alt,space,spawn,qs -c noctalia-shell ipc call launcher toggle

# exit
bind=SUPER,m,quit
bind=ALT,q,killclient,

# switch layout
bind=SUPER+ALT,s,setlayout,scroller
bind=SUPER+ALT,t,setlayout,tile

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

# move scroller stack
bind=SUPER+ctrl,left,scroller_stack,left
bind=SUPER+ctrl,right,scroller_stack,right


# swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=ALT,a,togglemaximizescreen,
bind=ALT,f,togglefullscreen,
bind=SUPER,f,togglefloating,
bind=SUPER,o,toggleoverlay,
bind=SUPER+SHIFT,I,restore_minimized
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# scroller layout
bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,

# switch view
bind=Ctrl,1,view,1,0
bind=Ctrl,2,view,2,0
bind=Ctrl,3,view,3,0
bind=Ctrl,4,view,4,0
bind=Ctrl,5,view,5,0
bind=Ctrl,6,view,6,0
bind=Ctrl,7,view,7,0
bind=Ctrl,8,view,8,0
bind=Ctrl,9,view,9,0

bind=Alt,1,tag,1,0
bind=Alt,2,tag,2,0
bind=Alt,3,tag,3,0
bind=Alt,4,tag,4,0
bind=Alt,5,tag,5,0
bind=Alt,6,tag,6,0
bind=Alt,7,tag,7,0
bind=Alt,8,tag,8,0
bind=Alt,9,tag,9,0

# monitor switch
bind=alt+shift,Left,focusmon,left
bind=alt+shift,Right,focusmon,right

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client

bind=super,space,switch_keyboard_layout


