# Appearance
# https://www.useotools.com/color-converter for color conversion into 8bit hex format
gappih=5
gappiv=5
gappoh=10
gappov=10
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=2

# layout support:
# tile,scroller,grid,deck,monocle,center_tile,vertical_tile,vertical_scroller
tagrule=id:1,layout_name:vertical_scroller
tagrule=id:2,layout_name:vertical_scroller
tagrule=id:3,layout_name:vertical_scroller
tagrule=id:4,layout_name:vertical_scroller
tagrule=id:5,layout_name:vertical_scroller
tagrule=id:6,layout_name:vertical_scroller
tagrule=id:7,layout_name:vertical_scroller
tagrule=id:8,layout_name:vertical_scroller
tagrule=id:9,layout_name:vertical_scroller

# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi
