# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x121316ff
bordercolor = 0x8d9199ff
focuscolor = 0xa4c9ffff
maximizescreencolor = 0xbcc7dbff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xd9bde3ff
globalcolor = 0x004883ff
overlaycolor = 0x3c4758ff
