# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x242424ff
bordercolor = 0x726983ff
focuscolor = 0x3584e4ff
maximizescreencolor = 0x1b467cff
urgentcolor = 0xc01c28ff
scratchpadcolor = 0xffffffff
globalcolor = 0x042f62ff
overlaycolor = 0x082345ff
