# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x0b0e14ff
bordercolor = 0x595f6aff
focuscolor = 0xe6b450ff
maximizescreencolor = 0xaad94cff
urgentcolor = 0xd95757ff
scratchpadcolor = 0x39bae6ff
globalcolor = 0x7d5507ff
overlaycolor = 0x49670bff
